name: "temp testing"
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, closed]
    paths:
        - README.md

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
